=== luk1nov/Epam_Task2/resources/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/devices"
        xmlns:tns="http://www.example.org/devices"
        elementFormDefault="qualified">

    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="device" type="tns:Device" abstract="true"/>
    <element name="storage-device" type="tns:storageDevice" substitutionGroup="tns:device"/>
    <element name="audio-device" type="tns:audioDevice" substitutionGroup="tns:device"/>


    <complexType name="Device" >
        <sequence>
            <element name="name" type="string"/>
            <element name="brand" type="tns:Brand"/>
            <element name="price" type="double"/>
            <element name="type" type="tns:Type"/>
            <element name="critical" type="boolean" default="false"/>
        </sequence>
        <attribute name="device-id" type="tns:deviceID" use="required"/>
        <attribute name="title" type="string" use="optional"/>
    </complexType>

    <complexType name="storageDevice">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="storage-capacity" type="positiveInteger"/>
                    <element name="write-speed" type="positiveInteger"/>
                    <element name="reading-speed" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="audioDevice">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="wireless" type="boolean"/>
                    <element name="surround" type="tns:Surround"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <simpleType name="deviceID">
        <restriction base="ID">
            <pattern value="\w\d{1,6}"/>
        </restriction>
    </simpleType>

    <complexType name="Type">
        <sequence>
            <element name="peripheral" type="boolean"/>
            <element name="power-usage" type="positiveInteger"/>
            <element name="cooler" type="boolean"/>
            <element name="ports" type="tns:Ports" />
        </sequence>
    </complexType>

    <complexType name="Ports">
        <sequence>
            <element name="com" type="boolean"/>
            <element name="usb" type="boolean"/>
            <element name="lpt" type="boolean"/>
        </sequence>
    </complexType>

    <simpleType name="Surround">
        <restriction base="string">
            <enumeration value="5.1"/>
            <enumeration value="7.1"/>
            <enumeration value="9.1"/>
        </restriction>
    </simpleType>

    <simpleType name="Brand">
        <restriction base="string">
            <enumeration value="Razer"/>
            <enumeration value="Sony"/>
            <enumeration value="HyperX"/>
            <enumeration value="Logitech"/>
            <enumeration value="Oclick"/>
            <enumeration value="Sandisk"/>
            <enumeration value="WD"/>
        </restriction>
    </simpleType>
    
</schema>

=== luk1nov/Epam_Task2/resources/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/devices"
         xsi:schemaLocation="http://www.example.org/tariffs schema.xsd">

    <audio-device device-id="a1" title="headset razer">
        <name>Headset</name>
        <brand>Razer</brand>
        <price>109.99</price>
        <type>
            <peripheral>true</peripheral>
            <power-usage>2</power-usage>
            <cooler>false</cooler>
            <ports>
                <com>false</com>
                <usb>true</usb>
                <lpt>false</lpt>
            </ports>
        </type>
        <critical>false</critical>
        <warranty>2023-01-01</warranty>
        <wireless>false</wireless>
        <surround>5.1</surround>
    </audio-device>

    <audio-device device-id="a2" title="microphone hyperx">
        <name>Microphone</name>
        <brand>HyperX</brand>
        <price>129.99</price>
        <type>
            <peripheral>true</peripheral>
            <power-usage>6</power-usage>
            <cooler>false</cooler>
            <ports>
                <com>false</com>
                <usb>true</usb>
                <lpt>false</lpt>
            </ports>
        </type>
        <critical>false</critical>
        <warranty>2023-03-01</warranty>
        <wireless>false</wireless>
        <surround>9.1</surround>
    </audio-device>

    <audio-device device-id="a3" title="headphones logitech">
        <name>Headphones</name>
        <brand>Logitech</brand>
        <price>89.99</price>
        <type>
            <peripheral>true</peripheral>
            <power-usage>3</power-usage>
            <cooler>false</cooler>
            <ports>
                <com>false</com>
                <usb>true</usb>
                <lpt>false</lpt>
            </ports>
        </type>
        <critical>false</critical>
        <warranty>2023-03-01</warranty>
        <wireless>true</wireless>
        <surround>7.1</surround>
    </audio-device>

    <storage-device device-id="s1" title="ssd western-digital">
        <name>SSD</name>
        <brand>WD</brand>
        <price>149.0</price>
        <type>
            <peripheral>false</peripheral>
            <power-usage>20</power-usage>
            <cooler>true</cooler>
            <ports>
                <com>false</com>
                <usb>false</usb>
                <lpt>false</lpt>
            </ports>
        </type>
        <critical>false</critical>
        <warranty>2022-09-01</warranty>
        <storage-capacity>256</storage-capacity>
        <write-speed>1800</write-speed>
        <reading-speed>1600</reading-speed>
    </storage-device>

    <storage-device device-id="s2" title="hdd sandisk">
        <name>HDD</name>
        <brand>Sandisk</brand>
        <price>1439.0</price>
        <type>
            <peripheral>false</peripheral>
            <power-usage>25</power-usage>
            <cooler>false</cooler>
            <ports>
                <com>true</com>
                <usb>false</usb>
                <lpt>false</lpt>
            </ports>
        </type>
        <critical>true</critical>
        <warranty>2023-01-01</warranty>
        <storage-capacity>1024</storage-capacity>
        <write-speed>3600</write-speed>
        <reading-speed>3200</reading-speed>
    </storage-device>

    <storage-device device-id="s3" title="hdd western-digital">
        <name>HDD</name>
        <brand>WD</brand>
        <price>1449.0</price>
        <type>
            <peripheral>false</peripheral>
            <power-usage>15</power-usage>
            <cooler>false</cooler>
            <ports>
                <com>false</com>
                <usb>false</usb>
                <lpt>true</lpt>
            </ports>
        </type>
        <critical>false</critical>
        <warranty>2023-01-01</warranty>
        <storage-capacity>512</storage-capacity>
        <write-speed>2000</write-speed>
        <reading-speed>1700</reading-speed>
    </storage-device>
</devices>
